Update direnv use scripts

diff --git a/tasks/dotfiles.yml b/tasks/dotfiles.yml
--- a/tasks/dotfiles.yml
+++ b/tasks/dotfiles.yml
@@ -83,51 +83,85 @@
   ansible.builtin.copy:
     dest: "{{ direnv_config_dir }}/use_sops.sh"
     content: |
-      ####################################################################
-      # Generated by ansible
-      ####################################################################
-      # Retrieve the sops age key from bitwarden
+      ################################################################################
+      # Retrieve age key files from Bitwarden
       #
       # Globals:
-      #   SOPS_AGE_KEY_FILE
+      #   USE_SOPS_DISABLE
       # Arguments:
-      #   Client name
-      ####################################################################
-      ### Generated by ansible ###
+      #   Client name 
+      #   Format for the Vaultwarden item, default to '${client} - Age - Private Key'
+      ################################################################################
       use_sops() {
         local client
+        local format
+
+        local red
+        local yellow
+        local no_color
+
+        local key_name
+
+        # Rename arguments
         client=$1
+        export client
+        format=${2:-${client} - Age - Private Key}
+
+        # Define colors
+        red="\033[31m"
+        yellow="\033[33m"
+        no_color="\033[0m"
+
+        # Define variables
+        key_name=$(echo $format | envsubst)
+
+        # The SOPS file already exists
+        if [ -f "$SOPS_AGE_KEY_FILE" ]; then
+          return
+        fi
+
+        if [ -n "${USE_SOPS_DISABLE:-}" ]; then
+          echo -e "${yellow}Disabled use_sops 'USE_SOPS_DISABLE'${no_color}"
+          return
+        fi
 
         if [ -z "$client" ]; then
-          echo "Missing client"
-          exit 0
+          echo -e "${red}Missing client${no_color}" 
+          return
         fi
 
         if [ -z "$SOPS_AGE_KEY_FILE" ]; then
-          echo "Missing SOPS_AGE_KEY_FILE variable"
-          exit 0
+          echo -e "${red}Missing SOPS_AGE_KEY_FILE variable${no_color}" 
+          return
         fi
 
-        # The SOPS file already exists
-        if [ ! -f "$SOPS_AGE_KEY_FILE" ]; then
-          key_name="${client} - Age - Private Key"
+        # Get Bitwarden session token
+        if [ -z "$BW_SESSION" ]; then
+          BW_SESSION=$(bw unlock --raw)
 
-          if [ -z "$BW_SESSION" ]; then
-            BW_SESSION=$(bw unlock --raw)
-
-            # Error in the login
-            if [ $? -ne 0 ]; then
-              exit 0
-            fi
-
-            # Export for bw cli
-            export BW_SESSION
+          # Error in the login
+          if [ $? -ne 0 ]; then
+            return
           fi
 
-          if ! bw get password "$key_name" > $SOPS_AGE_KEY_FILE 2> /dev/null; then
-            echo "Key for client '${client}' not found"
-            rm "$SOPS_AGE_KEY_FILE"
-          fi
+          # Export for bw cli
+          export BW_SESSION
+        fi
+
+        echo "# created: $(date +%Y-%m-%dT%T%:z)" >> "$SOPS_AGE_KEY_FILE"
+        username=$(bw get username "$key_name" 2> /dev/null)
+        if [ $? -eq 0 ]; then
+          echo "# public key: $username" >> "$SOPS_AGE_KEY_FILE"
+        else
+          echo -e "${yellow}Public key not found as username at '${key_name}'${no_color}"
+        fi
+
+        password=$(bw get password "$key_name" 2> /dev/null)
+        if [ $? -eq 0 ]; then
+          echo "$password" >> "$SOPS_AGE_KEY_FILE"
+        else
+          echo -e "${red}Private key not found as password at '${key_name}'${no_color}"
+          rm "$SOPS_AGE_KEY_FILE"
         fi
       }
 -
@@ -135,8 +169,6 @@
   ansible.builtin.copy:
     dest: "{{ direnv_config_dir }}/use_aws_sso_login.sh"
     content: |
-      ####################################################################
-      # Generated by ansible
       ####################################################################
       # Execute, if is needed, the aws sso login command for every profile
       #
@@ -149,37 +181,57 @@
       use_aws_sso_login() {
         local sso_ttl
         local profiles
+
+        local red
+        local yellow
+        local green
+        local no_color
+
+
         sso_ttl=${1:-60}
         profiles=""
 
+        # Define colors
+        red="\033[31m"
+        yellow="\033[33m"
+        green="\033[32m"
+        no_color="\033[0m"
+
         if [ -n "${USE_AWS_SSO_LOGIN_DISABLE:-}" ]; then
-          echo -e "\033[33mDisabled auto login by variable 'USE_AWS_SSO_LOGIN_DISABLE'\033[0m"
+          echo -e "${yellow}Disabled auto login by variable 'USE_AWS_SSO_LOGIN_DISABLE'${no_color}"
           return
         fi
 
+        # Retrieve the expiration timestamp
         [ -f "$PWD/.sso-login-expire" ] && sso_login_expire=$(cat "$PWD/.sso-login-expire")
 
-        if [ "${sso_login_expire:-0}" -lt "$(date +%s)" ]; then
-          profiles=$(env | { grep PROFILE || test $? = 1; } | { grep mw_ || test $? = 1; } | cut -d"=" -f 2 | sort | uniq)
+        # Check if the session is expired
+        if [ ! "${sso_login_expire:-0}" -lt "$(date +%s)" ]; then
+          echo -e "${green}AWS SSO session until $(date -d @"${sso_login_expire}" +%H:%M:%S)${no_color}"
+          return
+        fi
 
-          if [ -n "${profiles}" ]; then
-            echo -e "\033[31mExpired AWS SSO session\033[0m"
-            for profile in $profiles; do
-              if [ -n "${USE_AWS_SSO_LOGIN_DRY_RUN:-}" ]; then
-                echo aws sso login --profile "${profile}"
-              else
-                aws sso login --profile "${profile}"
-              fi
-            done
-            if [ -n "${USE_AWS_SSO_LOGIN_DRY_RUN:-}" ]; then
-              echo "date +%s --date='+${sso_ttl} minutes' > $PWD/.sso-login-expire"
-            else
-              date +%s --date="+${sso_ttl} minutes" > "$PWD/.sso-login-expire"
-            fi
+        # Retrieve all the profiles that match two rules
+        profiles=$(env | { grep PROFILE || test $? = 1; } | { grep mw_ || test $? = 1; } | cut -d"=" -f 2 | sort | uniq)
+
+        if [ -z "${profiles}" ]; then
+          echo -e "${yellow}No profiles found${no_color}"
+          return
+        fi
+
+        echo -e "${red}Expired AWS SSO session${no_color}"
+
+        for profile in $profiles; do
+          if [ -n "${USE_AWS_SSO_LOGIN_DRY_RUN:-}" ]; then
+            echo aws sso login --profile "${profile}"
           else
-            echo -e "\033[33mNo profiles found\033[0m"
+            aws sso login --profile "${profile}"
           fi
+        done
+
+        if [ -n "${USE_AWS_SSO_LOGIN_DRY_RUN:-}" ]; then
+          echo "date +%s --date='+${sso_ttl} minutes' > $PWD/.sso-login-expire"
         else
-          echo -e "\033[32mAWS SSO session until $(date -d @"${sso_login_expire}" +%H:%M:%S)\033[0m"
+          date +%s --date="+${sso_ttl} minutes" > "$PWD/.sso-login-expire"
         fi
       }
