Agrego use_terraform a direnv

diff --git a/tasks/dotfiles.yml b/tasks/dotfiles.yml
--- a/tasks/dotfiles.yml
+++ b/tasks/dotfiles.yml
@@ -49,3 +49,32 @@
         url: "{{ item }}"
         dest: "{{ workstation_dotfiles_fonts_directory }}/{{ item | basename }}"
       loop: "{{ workstation_dotfiles_fonts }}"
+-
+  name: "Set direnv configuration directory"
+  set_fact:
+    direnv_config_dir: "{{ ansible_user_dir }}/.config/direnv/lib"
+
+-
+  name: "Create direnv configuration directory"
+  file:
+    path: "{{ direnv_config_dir }}"
+    state: directory
+    mode: "0755"
+-
+  name: "Setup direnv use_terraform"
+  ansible.builtin.copy:
+    dest: "{{ direnv_config_dir }}/use_terraform.sh"
+    content: |
+      ### Generated by ansible ###
+      use_terraform() {
+        DIR="$(expand_path .)/.mw-bin"
+        PATH_add "$DIR"
+        mkdir -p "$DIR"
+        if type -p tfswitch > /dev/null ; then
+          tfswitch -b "$DIR/terraform"
+        else
+          echo
+          echo "tfswitch is required!" >&2
+          echo
+        fi
+      }
